### ISSUE TITLE
Cannot access X's profile

### ISSUE THREAD

**Issue by aubertc** [DisCoTec/discotec.github.io#12]
*This may be a problem to discuss with the SC…*

I cannot access discotec's profile on X since X is now reserved to registered users:

![Screenshot_20241209_135313](https://github.com/user-attachments/assets/48fec374-046c-4fed-a46c-79842abff23a)

Consider [switching to mastodon](https://bewegung.social/@neuSoM/113618197334651847)?

**Comment by basvdheuvel** [comment]
You're right. @MatthewAlanLeBrun has been trying to register for mastodon but hasn't been able to. Any experience?

**Comment by MatthewAlanLeBrun** [comment]
I've applied for a domain on mastodon.education since I thought that would be the most appropriate. From what I read however, requests to this server are human-approved and it is taking quite a while (I've applied for the domain well over a month ago now). 

I'm not aware of any other academia focused servers; however, given how long it is taking, maybe we should go for a generic mastodon.social domain. If in the future the request gets approved, I think it is possible to switch servers.

**Comment by basvdheuvel** [comment]
I'm a bit confused: don't we want to post on existing mastodon's? How are our posts going to reach a public on our own server? Or am I misunderstanding things?

**Comment by aubertc** [comment]
I've been using https://lipn.info/ for a while and enjoys it.  It is run by my Alma Matter, [le laboratoire d’informatique de Paris Nord](https://lipn.univ-paris13.fr/). The admin, Pierre Boudes ( boudes@univ-paris13.fr ) is quite responsive and does a good job (IMHO) at maintaining the server running. I think they do accept profile for conferences, in any case they have "CNRS section" (https://lipn.info/@CoNRS6)

**Comment by MatthewAlanLeBrun** [comment]
Thanks for the suggestion Clément! I will set it up on lipn.

**Comment by MatthewAlanLeBrun** [comment]
Hooray Mastodon has been approved! Follow and share [@DisCoTecConf](https://lipn.info/@DisCoTecConf)
